# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:45
from __future__ import unicode_literals

from django.db import migrations
import csv
import names

movie_PATH = 'u.item'
rater_PATH = 'u.user'
ratings_PATH = 'u.data'


class Migration(migrations.Migration):

    def load_movies(apps, schema_editor):
        Movies = apps.get_model("recommend_app", "Movies")

        with open(movie_PATH, 'r', encoding='latin-1') as f:
            categories = {'fieldnames': ('movie_id',
                                         'title',
                                         'release_date',
                                         'video_release',
                                         'imdb'), 'delimiter': '|'}
            reader = csv.DictReader(f, **categories)
            for row in reader:
                m = Movies(id=row['movie_id'], title=row['title'], release_date=row['release_date'], video_release=row['video_release'], imdb=row['imdb'])
                m.save()

    def load_raters(apps, schema_editor):
        Rater = apps.get_model("recommend_app", "Rater")
        name_bank = []

        with open(rater_PATH, 'r') as f:
            categories = {'fieldnames': ('rater_id', 'age', 'gender'),
                          'delimiter': '|'}
            reader = csv.DictReader(f, **categories)
            for row in reader:
                while True:
                    if row['gender'] == 'M':
                        name = names.get_full_name(gender='male')
                    else:
                        name = names.get_full_name(gender='female')
                    if name not in name_bank:
                        name_bank.append(name)
                        break

                r = Rater(id=row['rater_id'], name=name,
                          age=row['age'], gender=row['gender'])
                r.save()

    def load_ratings(apps, schema_editor):
        Movies = apps.get_model("recommend_app", "Movies")
        Rater = apps.get_model("recommend_app", "Rater")
        Ratings = apps.get_model("recommend_app", "Ratings")

        with open(ratings_PATH, 'r') as f:
            categories = {'fieldnames': ('rater_id', 'movie_id', 'rating',
                          'rate_date'), 'delimiter': '\t'}
            reader = csv.DictReader(f, **categories)
            for row in reader:
                u = Rater.objects.get(id=row['rater_id'])
                m = Movies.objects.get(id=row['movie_id'])

                r = Ratings(rating=row['rating'], rate_date=row['rate_date'],
                            movie=m, rater=u)
                r.save()

    dependencies = [
        ('recommend_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_movies),
        migrations.RunPython(load_raters),
        migrations.RunPython(load_ratings),
    ]
