# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 22:54
from __future__ import unicode_literals

from django.db import migrations

import csv

ratings_PATH = 'u.data'


class Migration(migrations.Migration):

    def load_ratings(apps, schema_editor):
        Movies = apps.get_model("recommend_app", "Movies")
        Rater = apps.get_model("recommend_app", "Rater")
        Ratings = apps.get_model("recommend_app", "Ratings")

        with open(ratings_PATH, 'r') as f:
            categories = {'fieldnames': ('rater_id', 'movie_id', 'rating',
                          'rate_date'), 'delimiter': '\t'}
            reader = csv.DictReader(f, **categories)
            for row in reader:
                u = Rater.objects.get(id=row['rater_id'])
                m = Movies.objects.get(id=row['movie_id'])

                r = Ratings(rating=row['rating'], rate_date=row['rate_date'],
                            movie=m, rater=u)
                r.save()

    dependencies = [
        ('recommend_app', '0002_auto_20170318_2035'),
    ]

    operations = [

    ]
