# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0003_auto_20170318_2254'),
        ('recommend_app', '0004_auto_20170318_2256'),
    ]

    operations = [
    ]
